# -*- coding: utf-8 -*-
"""Copia de Clase.8- 08 de septiembre

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EMn_N-owiRO-sPsRkPFngQlojuaWgTqr
"""



"""<center>

#**COLEGIO SIGLO XXI - EL SOCORRO**
#**PRESENTADO A : ING PAOLA ANDREA QUINTERO**
#**PRESENTADO POR : CATALINA RANGEL MARÍN**
#**GRADO DÉCIMO**
#**8 SEPTIEMBRE 2022**

#**¿Qué es Python?**
# Es un lenguaje de programación de alto nivel que se utiliza para desarrollar aplicaciones de todo tipo. A diferencia de otros lenguajes como Java o .NET, se trata de un lenguaje interpretado, es decir, que no es necesario compilarlo para ejecutar las aplicaciones escritas en Python, sino que se ejecutan directamente por el ordenador utilizando un programa denominado interpretador, por lo que no es necesario “traducirlo” a lenguaje máquina.

#**Fecha de lanzamiento**: 1991

#**Creadores**:Guido Van Rossum

#**Recuperado de:**https://www.becas-santander.com/es/blog/python-que-es.html
"""

print("Esto es una suma")
numero_uno= 5
numero_dos= 9
resultado= numero_uno + numero_dos
print(resultado)

print("Esto es una resta")
numero_uno= 17
numero_dos= 9
resultado= numero_uno - numero_dos
print(resultado)

print("Esto es una multiplicación")
numero_uno= 32
numero_dos= 6
resultado= numero_uno * numero_dos
print(resultado)

print("Esto es una división")
numero_uno= 80
numero_dos= 4
resultado= numero_uno / numero_dos
print(resultado)

"""#**Ejercicios de Tipos de Datos Simples**"""

peso = input("¿cuál es tu peso en kg?")
estatura = input("¿cuál es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("tu índice de masa corporal es" + str(imc))

"""##Ejercicio 1##
Escribir un programa que pregunte el nombre del usuario en la consola y un número entero e imprima por pantalla el líneas distintas el nombre del usuario tantas veces como el número introducido.
"""

nombre = input("¿cómo te llamas? ")
n = input("Introduce un número entero:")
print((nombre + "\n") * int(n))

"""##Ejercicio 2##
Escribir un programa que pida al usuario su peso (en kg)y estatura (en metros)
,calcule el índice de masa corporal y lo almacena en una variable, e imprima por pantalla la frase 'Tu índice de masa corporal es <imc>' donde '<imc>' es el índice de masa corporal calculado redondeado con dos decimales.
"""

peso = input("¿cuál es tu peso en kg?")
estatura = input("¿cuál es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("Tu índice de masa corporal es " + str(imc))

"""#**LIBRERÍAS EN PYTHON**"""